<div class="category-description__left">
    <div class="content-brand-story">
        <div class="products-brand">
            <div class="content-brandstory">
                <div class="item-brandstory">
                    <div class="video-brandstory"> 
                        <div class="video-catalog">
                            <div class="video-catalog">
                                <iframe title="YouTube video player" src="//www.youtube.com/embed/-MIOvNg6wY0" width="855" height="523" frameborder="0" allowfullscreen="allowfullscreen"></iframe>
                            </div>
                        </div>
                    </div>
                    <div class="item-rows-brandstory">
                        <h2 class="category-description__left_title">UV Porcelain+</h2>
                        <div class="content-img-brandstory">

                        </div>
                        <div class="content-chose-brandstory">
                            <p class="mb-4 text-sm leading-normal lg:text-base md:mb-6">UV Porcelain+ sets the new benchmark for oral skin supplements with its Triple Action formulation, that protects you from harmful UV rays while working to whiten and brighten your skin.</p>
                            <ul>
                                <li class="pl-8 mb-2 text-sm leading-6 lg:text-base list-check">US FDA Certified</li>
                                <li class="pl-8 mb-2 text-sm leading-6 lg-text-base list-check">Manufactured in USA</li>
                                <li class="pl-8 text-sm leading-6 lg:text-base list-check">Clinically formulated</li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>