<div class="banner-content">  
    <div class="page-title-wrapper">
        <h1 class="page-title" id="page-title-heading" aria-labelledby="page-title-heading toolbar-amount">
            <span class="base" data-ui-id="page-title-wrapper">Professional Products</span>
        </h1> 
    </div>  
    <div class="breadcrumbs">
        <ul class="items"> 
            <li class="item home"> 
                <a href="https://magento2.com/" title="Go to Home Page">Home</a> 
            </li>  
            <li class="item category8"> 
                <strong>Professional Products</strong> 
            </li> 
        </ul>
    </div>
</div>
<div class="category-image">
    <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/profress/Mask%20Group%202.png" alt="About Us" title="About Us" class="image">
</div>
