<div class="session-professional4">
    <div class="container">
        <div class="widget block block-static-block">
            <div class="container-professional-address">
                <h3>Available At These Clinics</h3>
                <div class="content-address north">
                    <div class="content-address-title">North</div>
                    <div class="content-address-all" style="display: none;">
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">&nbsp;</div>
                            </div>
                            <div class="content-address-map">&nbsp;</div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">57 Medical Clinic (Yishun)</h5>
                                    <div class="tab-address local current"><a href="https://g.page/57medicalyis?share"
                                            target="_blank" rel="noopener">618 Yishun Ring road #01-3238, Singapore
                                            760618</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6235 3490">+65 6235 3490</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.5951048811266!2d103.83343081477456!3d1.4188080617451766!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da155c80c197f3%3A0xe7156c8e9384abaf!2s57%20Medical%20Clinic%20(Yishun)!5e0!3m2!1sen!2sin!4v1636712482282!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                    </div>
                </div>
                <!-- address East -->
                <div class="content-address east">
                    <div class="content-address-title">East</div>
                    <div class="content-address-all">
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">Aesthetic Works Medical&nbsp;</h5>
                                    <div class="tab-address local"><a href="https://g.page/aestheticworks?share"
                                            target="_blank" rel="noopener">80 Marine Parade Rd, #07-09, Singapore
                                            449269</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6910  8850">+65 6910 8850</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.789054306449!2d103.90296651475396!3d1.3014701990507616!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1871caf80887%3A0x92a641e3656e7578!2sAesthetic%20Works!5e0!3m2!1sen!2ssg!4v1649049623693!5m2!1sen!2ssg"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">57 Medical Clinic (Parkway Centre)</h5>
                                    <div class="tab-address local"><a
                                            href="https://www.google.com/maps/place/57+Medical+Clinic+(Parkway+Centre)/@1.3018462,103.9038734,17z/data=!3m1!4b1!4m5!3m4!1s0x31da19b88a00968d:0xbc2925e0f967da2d!8m2!3d1.3018408!4d103.9060621">1
                                            Marine Parade Central, #02-05, Singapore 449408</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6214 9612">+65 6214 9612</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.7884595863725!2d103.90387341534915!3d1.3018461620889972!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da19b88a00968d%3A0xbc2925e0f967da2d!2s57%20Medical%20Clinic%20(Parkway%20Centre)!5e0!3m2!1sen!2ssg!4v1646307096456!5m2!1sen!2ssg"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                    </div>
                </div>
                <div class="content-address central">
                    <div class="content-address-title">Central</div>
                    <div class="content-address-all">
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">Veritas Medical Aesthetics</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/EdhEXDEUywokzURp9"
                                            target="_blank" rel="noopener">13 Stamford Road, #b2-35 Capitol Piazza,
                                            Singapore 178905</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6904 5960">+65 6904 5960</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.801340119826!2d103.84972406477496!3d1.2936790621136571!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1931b184893b%3A0x89a01ece9c1413d9!2sVeritas%20Medical%20Aesthetics!5e0!3m2!1sen!2sin!4v1636713318685!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">Family Medicine Clinic</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/oezjTFFVrxp1wCX88"
                                            target="_blank" rel="noopener">133, New Bridge Road, #02-09, Chinatown
                                            Point, Singapore 059413</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6225 5155">+65 6225 5155</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.8153602820807!2d103.84242661477488!3d1.284730362139035!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da190a7da29809%3A0xcc66a434bc515bd2!2sFamily%20Medicine%20Clinic%20Chinatown!5e0!3m2!1sen!2sin!4v1636713427739!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">Orchard Group Clinic</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/u6RKstrfxrEqqQYp6"
                                            target="_blank" rel="noopener">545 Orchard Road, #12-04 Far East Shopping
                                            Centre, Singapore 238882</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6734 4989">+65 6734 4989</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d255282.0485561775!2d103.69005224552403!3d1.3059172594089992!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da198cff58f201%3A0x6fc9ec598b201c95!2sOrchard%20Group%20Clinic!5e0!3m2!1sen!2sin!4v1636713507660!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">Goodhealth TCM Clinic</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/3mpkn1eWSYFKgV3Q7"
                                            target="_blank" rel="noopener">150 Orchard Road, #03-45 Orchard Plaza,
                                            Singapore 23884</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 8818 6208">+65 8818 6208</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.789750006122!2d103.83891081477493!3d1.3010302620927277!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da16e6a8ef8bcb%3A0xae3cff7271e55e3f!2sGoodhealth%20TCM%20Clinic!5e0!3m2!1sen!2sin!4v1636713614419!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">New Health Family Clinic</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/6thD8JbyxiTNrmfbA"
                                            target="_blank" rel="noopener">Blk 108 Depot Road, #01-08 Depot Height
                                            Shopping Centre, Singapore 100108</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6278 6200">+65 6278 6200</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.820639843102!2d103.80811291477498!3d1.2813443621485932!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1bd75fe319bf%3A0x75af8e1e4ec61f1a!2sNew%20Health%20Family%20Clinic!5e0!3m2!1sen!2sin!4v1636713758916!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">Beo Crescent Clinic &amp; Surgery</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/6pWEhpq2sWYXK1jV8"
                                            target="_blank" rel="noopener">40 Beo Cres, #01-02, Singapore 160040</a>
                                    </div>
                                    <div class="tab-address phone"><a href="tel:+65 6275 0269">+65 6275 0269</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.8087321554476!2d103.82558921477495!3d1.2889686621270333!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1978aac27ab5%3A0xb9403e964a2a2103!2sBeo%20Crescent%20Clinic%20%26%20Surgery!5e0!3m2!1sen!2sin!4v1636713806441!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">Gong Surgery Pte Ltd</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/kvcf1iYPRPzf2qvz8"
                                            target="_blank" rel="noopener">6 Napier Road, #05-16 Gleneagles Medical
                                            Centre Singapore 258499</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6472 5933">+65 6472 5933</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.77928752152!2d103.81801281477495!3d1.3076307620738337!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1a2022718ebd%3A0x816ff866a8627a98!2sGong%20Surgery%20Pte.%20Ltd.!5e0!3m2!1sen!2sin!4v1636713978788!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">The Health Advisory Clinic</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/RLP8XBKaZPUWuLms5"
                                            target="_blank" rel="noopener">One Raffles Place #04-49/50 Singapore
                                            048616</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 9886 6442">+65 9886 6442</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.8158638908585!2d103.8487931147749!3d1.2844077621399412!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1930c527a1d1%3A0xaddd6e54a3856735!2sThe%20Health%20Advisory%20Clinic%20-%20Women's%20Health%20%7C%20STD%2FHIV%20Testing!5e0!3m2!1sen!2sin!4v1636714041621!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">Cosmopolitan Clinic</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/zXxMk1C1Ltxzerxz9"
                                            target="_blank" rel="noopener">25 Lor Telok Singapore 049037</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6327 3773">+65 6327 3773</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.812458872372!2d103.8465133147749!3d1.2865873621337698!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da190bb357479f%3A0xee69af45440f5768!2sCosmopolitan%20Clinic%20Pte%20Ltd!5e0!3m2!1sen!2sin!4v1636714103220!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">57 Medical Clinic (Geylang Bahru)</h5>
                                    <div class="tab-address local"><a href="https://g.page/57Med?share" target="_blank"
                                            rel="noopener">57 Geylang Bahru #01-3505 Singapore 330057</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6694 7078">+65 6694 7078</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.7539876365718!2d103.86674891477486!3d1.3234557620282896!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da19f403ea1fab%3A0x1326e0e7d6e84f6b!2s57%20Medical%20Clinic%20(Geylang%20Bahru)!5e0!3m2!1sen!2sin!4v1636714199991!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">P Tan Family Medicine Clinic</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/TuAnH3mV1bo4YFXK6"
                                            target="_blank" rel="noopener">BLK 503 Bishan Street 11, #01-464 Singapore
                                            570503</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6255 7545">+65 6255 7545</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.713185827178!2d103.8457839147748!3d1.348586061955114!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da17570dcb717d%3A0x35a5214ffa345ac9!2sP%20Tan%20Family%20Medicine%20Clinic!5e0!3m2!1sen!2sin!4v1636713903372!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                        <div class="full-contents">
                            <div class="content-fulltab">
                                <div class="content-address-tab">
                                    <h5 class="content-address-tab-title">1 Medical Teck Ghee</h5>
                                    <div class="tab-address local"><a href="https://goo.gl/maps/wxZwkMuH3qhQCuHt6"
                                            target="_blank" rel="noopener">410 Ang Mo Kio Ave 10 #01-837 Singapore
                                            560410</a></div>
                                    <div class="tab-address phone"><a href="tel:+65 6251 7030">+65 6251 7030</a></div>
                                </div>
                            </div>
                            <div class="content-address-map"><iframe style="border: 0;"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.689945948642!2d103.85245331477476!3d1.3626926619135875!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da171d149aaaab%3A0xfc2d85a87dc93c55!2s1%20Medical%20Teck%20Ghee!5e0!3m2!1sen!2sin!4v1636714287029!5m2!1sen!2sin"
                                    width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content-address central">
                <div class="content-address-title">West</div>
                <div class="content-address-all">
                    <div class="full-contents">
                        <div class="content-fulltab">
                            <div class="content-address-tab">
                                <h5 class="content-address-tab-title">Sherwood Aesthetics</h5>
                                <div class="tab-address local"><a href="https://g.page/sherwoodaestheticssg?share"
                                        target="_blank" rel="noopener">1 Jalan Anak Bukit, #01-08 Bukit Timah Plaza,
                                        Singapore 588996</a></div>
                                <div class="tab-address phone"><a href="tel:+65 1234 5678">+65 6737 3770</a></div>
                            </div>
                        </div>
                        <div class="content-address-map"><iframe style="border: 0;"
                                src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.729553051537!2d103.77642461477478!3d1.3385619619844287!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da11aa7866fbf1%3A0x501347e46221fab1!2sSherwood%20Aesthetics%20Pte%20Ltd!5e0!3m2!1sen!2sin!4v1636712712722!5m2!1sen!2sin"
                                width="600" height="450" allowfullscreen="allowfullscreen"></iframe></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script> 
    require(
    [
        'jquery'
    ],
    function($){
        $(document).ready(function() {
            $('.content-address-title').click(function(){
                $(this).next().slideToggle()
            })
        })
    }
)
</script>