<div class="session-professional2">
    <div class="container-full"> 
        <div class="widget block block-static-block">
            <div class="content-professional-tab">
                <div class="content-professional-slide" style="width: 582px;">
                    <img src="https://magento2.com/app/code/Testimonial/Slide/view/frontend/web/images/UV_Porcelain_Box_2_1.png" alt="">
                    <img src="https://magento2.com/app/code/Testimonial/Slide/view/frontend/web/images/UV_Porcelain_with_capsules.png" alt="">
                </div>
                <div class="tab-wrapper">
                    <div class="tabs-selected-wrapper">
                        <ul class="tabs category-listing">
                            <li class="tab-link tab-1 current" data-tab="tab-1">Overview</li>
                            <li class="tab-link tab-2 " data-tab="tab-2">Benefits</li>
                            <li class="tab-link tab-3" data-tab="tab-3">Ingredients</li>
                            <li class="tab-link tab-4" data-tab="tab-4">Directions of use</li>
                        </ul>
                        <div class="tab-content-info">
                            <div class="tab-content tab-1 current">Manufactured in USA. Certified by US FDA and clinically proven. An oral supplement (750mg per capsule) formulated to lighten overall skin tone, broad spectrum UVA and UVB protection, stimulate collagen and elastin production, and increase skin elasticity. 
                                <br><br>Size: 30 x 750mg Capsules
                            </div>
                            <div class="tab-content tab-2">
                                Benefits:
                                <br>✔ Proprietary Alpha-Porcelain formulation for skin whitening and brightening
                                <br>✔ PLE for protection against UV rays and reduced sun sensitivity
                                <br>✔ Proprietary collagen peptide for increased skin elasticity and reduced fine lines
                                <br><br>
                                Solutions for:
                                <br>✔ Dull and lack lustre skin
                                <br>✔ Age spots, stubborn melanin patches and uneven skin tone
                                <br>✔ Sunscreen and protection against UV rays (particularly suitable for those who are sensitive to topical sunblocks
                                <br>✔ Lack of skin elasticity
                            </div>
                            <div class="tab-content tab-3">L-Glutathione, Polypodium Leucotomos, Vitamin C, Collagen Peptide, Rice Bran, Alpha Porcelain, Magnesium Stearate

                            </div>
                            <div class="tab-content tab-4">Each 750mg capsule is hygienically package in individual blister. Recommended to be consumed once a day on an empty stomach and 30 minutes before sun exposure. Each complete box consists of 30 capsules.
                                    
                            </div>
                        </div>
                    </div>
                    <div class="addthis_inline_share_toolbox_7902" data-url="https://www.curatiq.com/professional-products/uv-porcelain.html" data-title="UV Porcelain+ - Professional Products | Curated Skincare &amp; Beauty Boutique Singapore | Curatiq" style="clear: both;">&nbsp;
                        <div id="atstbx" class="at-share-tbx-element addthis-smartlayers addthis-animated at4-show" aria-labelledby="at-9f9338a8-e8b4-41dd-be91-a272aaa327c4" role="region">
                            <span id="at-9f9338a8-e8b4-41dd-be91-a272aaa327c4" class="at4-visually-hidden">AddThis Sharing Buttons</span>
                            <div class="at-share-btn-elements">
                                <a role="button" tabindex="0" class="at-icon-wrapper at-share-btn at-svc-facebook" style="background-color: rgb(255, 255, 255); border-radius: 0px;">
                                    <span class="at4-visually-hidden">Share to Facebook</span>
                                    <span class="at-icon-wrapper" style="line-height: 20px; height: 20px; width: 20px;">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-facebook-1" class="at-icon at-icon-facebook" style="fill: rgb(102, 102, 102); width: 20px; height: 20px;">
                                            <title id="at-svg-facebook-1">Facebook</title>
                                            <g>
                                                <path d="M22 5.16c-.406-.054-1.806-.16-3.43-.16-3.4 0-5.733 1.825-5.733 5.17v2.882H9v3.913h3.837V27h4.604V16.965h3.823l.587-3.913h-4.41v-2.5c0-1.123.347-1.903 2.198-1.903H22V5.16z" fill-rule="evenodd">

                                                </path>
                                            </g>
                                        </svg>
                                    </span>
                                </a>
                                <a role="button" tabindex="0" class="at-icon-wrapper at-share-btn at-svc-twitter" style="background-color: rgb(255, 255, 255); border-radius: 0px;">
                                    <span class="at4-visually-hidden">Share to Twitter</span>
                                    <span class="at-icon-wrapper" style="line-height: 20px; height: 20px; width: 20px;">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-twitter-2" class="at-icon at-icon-twitter" style="fill: rgb(102, 102, 102); width: 20px; height: 20px;">
                                            <title id="at-svg-twitter-2">Twitter</title>
                                            <g>
                                                <path d="M27.996 10.116c-.81.36-1.68.602-2.592.71a4.526 4.526 0 0 0 1.984-2.496 9.037 9.037 0 0 1-2.866 1.095 4.513 4.513 0 0 0-7.69 4.116 12.81 12.81 0 0 1-9.3-4.715 4.49 4.49 0 0 0-.612 2.27 4.51 4.51 0 0 0 2.008 3.755 4.495 4.495 0 0 1-2.044-.564v.057a4.515 4.515 0 0 0 3.62 4.425 4.52 4.52 0 0 1-2.04.077 4.517 4.517 0 0 0 4.217 3.134 9.055 9.055 0 0 1-5.604 1.93A9.18 9.18 0 0 1 6 23.85a12.773 12.773 0 0 0 6.918 2.027c8.3 0 12.84-6.876 12.84-12.84 0-.195-.005-.39-.014-.583a9.172 9.172 0 0 0 2.252-2.336" fill-rule="evenodd">

                                                </path>
                                            </g>
                                        </svg>
                                    </span>
                                </a>
                                <a role="button" tabindex="0" class="at-icon-wrapper at-share-btn at-svc-pinterest_share" style="background-color: rgb(255, 255, 255); border-radius: 0px;">
                                    <span class="at4-visually-hidden">Share to Pinterest

                                    </span>
                                    <span class="at-icon-wrapper" style="line-height: 20px; height: 20px; width: 20px;">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-pinterest_share-3" class="at-icon at-icon-pinterest_share" style="fill: rgb(102, 102, 102); width: 20px; height: 20px;">
                                            <title id="at-svg-pinterest_share-3">Pinterest</title>
                                            <g>
                                                <path d="M7 13.252c0 1.81.772 4.45 2.895 5.045.074.014.178.04.252.04.49 0 .772-1.27.772-1.63 0-.428-1.174-1.34-1.174-3.123 0-3.705 3.028-6.33 6.947-6.33 3.37 0 5.863 1.782 5.863 5.058 0 2.446-1.054 7.035-4.468 7.035-1.232 0-2.286-.83-2.286-2.018 0-1.742 1.307-3.43 1.307-5.225 0-1.092-.67-1.977-1.916-1.977-1.692 0-2.732 1.77-2.732 3.165 0 .774.104 1.63.476 2.336-.683 2.736-2.08 6.814-2.08 9.633 0 .87.135 1.728.224 2.6l.134.137.207-.07c2.494-3.178 2.405-3.8 3.533-7.96.61 1.077 2.182 1.658 3.43 1.658 5.254 0 7.614-4.77 7.614-9.067C26 7.987 21.755 5 17.094 5 12.017 5 7 8.15 7 13.252z" fill-rule="evenodd">

                                                </path>
                                            </g>
                                        </svg>
                                    </span>
                                </a>
                                <a role="button" tabindex="0" class="at-icon-wrapper at-share-btn at-svc-email" style="background-color: rgb(255, 255, 255); border-radius: 0px;">
                                    <span class="at4-visually-hidden">Share to Email</span>
                                    <span class="at-icon-wrapper" style="line-height: 20px; height: 20px; width: 20px;">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 32 32" version="1.1" role="img" aria-labelledby="at-svg-email-4" class="at-icon at-icon-email" style="fill: rgb(102, 102, 102); width: 20px; height: 20px;">
                                            <title id="at-svg-email-4">Email</title>
                                            <g>
                                                <g fill-rule="evenodd"></g>
                                                <path d="M27 22.757c0 1.24-.988 2.243-2.19 2.243H7.19C5.98 25 5 23.994 5 22.757V13.67c0-.556.39-.773.855-.496l8.78 5.238c.782.467 1.95.467 2.73 0l8.78-5.238c.472-.28.855-.063.855.495v9.087z"></path><path d="M27 9.243C27 8.006 26.02 7 24.81 7H7.19C5.988 7 5 8.004 5 9.243v.465c0 .554.385 1.232.857 1.514l9.61 5.733c.267.16.8.16 1.067 0l9.61-5.733c.473-.283.856-.96.856-1.514v-.465z">

                                                </path>
                                            </g>
                                        </svg>
                                    </span>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    let tabs = document.querySelectorAll(".tabs.category-listing li");
    let tabContents = document.querySelectorAll(".tab-content-info .tab-content");

    tabs.forEach((tab, index) => {
    tab.addEventListener("click", () => {
        tabContents.forEach((content) => {
        content.classList.remove("current");
        });
        tabs.forEach((tab) => {
        tab.classList.remove("current");
        });
        tabContents[index].classList.add("current");
        tabs[index].classList.add("current");
    });
    });
</script>
<script>
	require(['jquery', 'jquery/ui', 'slick'], function($) {
    $(document).ready(function() {
        $(".content-professional-slide").slick({
            dots: true,
            infinite: true,
            slidesToShow: 1,
            slidesToScroll: 1
        });
    });
});
</script>	