<div class="about-need-help">
    <div class="new-about-bg">
        <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/shutterstock_1971928259-min.jpg" alt="" width="1965" height="650">
    </div>
    <div class="background-need-help">
        <div class="container-need-help">
            <div class="about-need-help">
                <h3>Need help deciding what is best for your skin?</h3>
                <p>Reach out to us for product recommendations, and detailed product information to help you make the right skincare and beauty choices.</p>
            </div>
            <div class="btn-general need-help-right">
                <div class="btn-need-help">
                    <a class="action submit primary" href="https://www.curatiq.com/contact-us/">CONTACT US</a>
                </div>
            </div>
        </div>
    </div>
</div>