<div class="session2">
    <div class="container"> 
        <div class="widget block block-static-block">
            <div class="content-inner-choose-us">
                <div class="title-about-choose-us">
                    <h3 class="title-choose-us">Why Choose Us</h3>
                </div>
                <div class="about-choose-us">
                    <div class="about-content about-choose">
                        <div class="item-rows">
                            <div class="img">
                                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/shutterstock_2032671119.jpg" alt="" width="491" height="400">
                            </div>
                            <div class="item-rows-content">
                                <h3 class="title-chose">Our Products Are Carefully Sourced &amp; Personally Tested</h3>
                                <div class="content-chose">
                                    <p>We believe in the brands we carry and love the results we have achieved by using their products. We carefully source each brand we introduce to our online boutique to offer you a streamlined range of only the best products. We also test each product internally to ensure they meet our expectations of delivering amazing results for you too!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="about-content about-choose quantity">
                        <div class="item-rows">
                            <div class="img">
                                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/shutterstock_2030339753.jpg" alt="" width="491" height="400">
                            </div>
                            <div class="item-rows-content">
                                <h3 class="title-chose">We Focus On Quality Not Quantity</h3>
                                <div class="content-chose">
                                    <p>Personally motivated by our own struggles with highly sensitive problem skin, we understand the difficulties you face when looking for the right skincare for your skin type and your skin concerns. Our curated boutique focuses on showcasing products with greater efficacy to address your skin concerns and give you the results you have been looking for.</p>
                                    <p>Finding suitable makeup for troubled skin can be a challenge. Our niche makeup collection features beauty products that have been thoughtfully formulated without any nasty ingredients. Simple, safe, and Curatiq-approved, 
                                        <a href="https://www.curatiq.com/">explore our collection today!</a>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="about-content about-choose">
                        <div class="item-rows">
                            <div class="img">
                                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/shutterstock_2004246308.jpg" alt="" width="491" height="400">
                            </div>
                            <div class="item-rows-content">
                                <h3 class="title-chose">We Do Things Differently</h3>
                                <div class="content-chose">
                                    <p>Inspired to make high-quality, better-performing skincare and beauty more accessible, we invest in building long-lasting relationships and mutual partnerships with leading global brand manufacturers and brand owners. We work directly with them to bring their products online just for you!</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>