<div class="session5">
    <div class="container-full"> 
        <div class="widget block block-static-block">
            <div class="about-start-shopping">
                <div class="container-about-shop">
                    <div class="btn-general about-shopping-right">
                        <div class="img-shopping">
                            <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/shutterstock_2032671098.jpg" alt="" width="960" height="636">
                        </div>
                    </div>
                    <div class="about-shopping-left">
                        <p>We pride ourselves on providing you with the best skincare solutions for your unique skin type and the right makeup that works wonders for your skin. Check out our curated skincare and beauty boutique today!</p>
                        <div class="btn-ourservices">
                            <a class="action submit primary" href="https://www.curatiq.com/e-shop.html/">E-SHOP</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>