<div class="session4">
    <div class="new-bg">
        <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/new-ss5-removebg-preview.png" alt="" width="625" height="399">
    </div>
    <div class="container"> 
        <div class="widget block block-static-block">
            <div class="content-core">
                <div class="title-about-core">
                    <h3 class="title-choose-us">Core Values</h3>
                </div>
                <div class="about-choose-core">
                    <div class="about-content about-core">
                        <div class="item-rows-core">
                            <div class="img-core">
                                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/10.png" alt="">
                            </div>
                            <div class="item-rows-content">
                                <h6 class="title-chose-core">Loyal</h6>
                                <div class="content-chose-core">
                                    <p>We are passionately dedicated to providing our customers with an unrivalled shopping experience for all their skincare and beauty needs.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="about-content about-core">
                        <div class="item-rows-core">
                            <div class="img-core">
                                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/9.png" alt="">
                            </div>
                            <div class="item-rows-content">
                                <h6 class="title-chose-core">Genuine</h6>
                                <div class="content-chose-core">
                                    <p>We forge long-term relationships by always having our customers and partners’ interests at heart</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="about-content about-core">
                        <div class="item-rows-core">
                            <div class="img-core">
                                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/8.png" alt="">
                            </div>
                        </div>
                        <div class="item-rows-content">
                            <h6 class="title-chose-core">Accessible</h6>
                            <div class="content-chose-core">
                                <p>Hard-to-source high-quality products can be easily purchased on our platform</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>