<div class="session3">
    <div class="container"> 
        <div class="widget block block-static-block">
            <div class="content-mission">
                <div class="title-about-mission">
                    <h3 class="title-choose-us">Mission &amp; Vision</h3>
                </div>
                <div class="about-choose-mission">
                    <div class="about-content about-mission">
                        <div class="item-rows-mission">
                            <div class="img">
                                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/Group_2941.png" alt="" width="62" height="70">
                            </div>
                            <div class="item-rows-content">
                                <h3 class="title-mission">Our Vision</h3>
                                <div class="content-chose-mission">
                                    <p>To be the trusted, one-stop online beauty retailer in the region.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="about-content about-mission">
                        <div class="item-rows-mission">
                            <div class="img">
                                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/Magento_Catalog/web/images/Group_2940.png" alt="" height="70">
                            </div>
                            <div class="item-rows-content">
                                <h3 class="title-mission">Our Mission</h3>
                                <div class="content-chose-mission">
                                    <p>To globally source for quality brands and introduce the latest products that deliver higher efficacy for all the different skin types and needs.</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>