<?php
$dataPostParam = '';
$blockObj= $block->getLayout()->createBlock('Magento\Customer\Block\Account\RegisterLink');
if ($block->isLoggedIn()) {
    $dataPostParam = sprintf(" data-post='%s'", $block->getPostParams());
}
?>
<div class="customer-welcome" name="customer-welcome">
    <div class="btn_login">
        <span> </span>
    </div>
    <div class="login_content" style="display: none">
        <ul>
            <li class="link authorization-link" data-label="<?= $escaper->escapeHtml(__('or')) ?>">
                <a <?= /* @noEscape */ $block->getLinkAttributes() ?>
                    <?= /* @noEscape */ $dataPostParam ?>><?= $escaper->escapeHtml($block->getLabel()) ?></a>
            </li>
            <li>
                <a href="<?= /* @noEscape */ $blockObj->getHref() ?>"> Register </a>
            </li>
        </ul>
    </div>

</div>
<script> 
    require(
    [
        'jquery'
    ],
    function($){
        $(document).ready(function() {
            $('.btn_login').click(function(){
                $(this).next().slideToggle()
            })
        })
    }
)
</script>
