<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $escaper \Magento\Framework\Escaper */
/** @var $configProvider \Magento\Search\ViewModel\ConfigProvider */
$configProvider = $block->getData('configProvider');
/** @var $helper \Magento\Search\Helper\Data */
$helper = $configProvider->getSearchHelperData();
$allowedSuggestion = $configProvider->isSuggestionsAllowed();
$quickSearchUrl = $allowedSuggestion ? $escaper->escapeUrl($helper->getSuggestUrl()) : '';
?>
<div class="search_header" name="search_header">
    <div class="btn_search"> 
        <span> </span>
    </div>
    <div class="block block-search" style="display: none">
        <div class="block block-title"><strong><?= $escaper->escapeHtml(__('Search')) ?></strong></div>
        <div class="block block-content">
            <form class="form minisearch" id="search_mini_form"
                action="<?= $escaper->escapeUrl($helper->getResultUrl()) ?>" method="get">
                <div class="field search">
                    <label class="label" for="search" data-role="minisearch-label">
                        <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                    </label>
                    <div class="control active">
                        <input id="search"
                            data-mage-init='{
                                "quickSearch": {
                                    "formSelector": "#search_mini_form",
                                    "url": "<?= /* @noEscape */ $quickSearchUrl ?>",
                                    "destinationSelector": "#search_autocomplete",
                                    "minSearchLength": "<?= $escaper->escapeHtml($helper->getMinQueryLength()) ?>"
                                }
                            }'
                            type="text"
                            name="<?= $escaper->escapeHtmlAttr($helper->getQueryParamName()) ?>"
                            value="<?= /* @noEscape */ $helper->getEscapedQueryText() ?>"
                            placeholder="<?= $escaper->escapeHtmlAttr(__('Search')) ?>"
                            class="input-text"
                            maxlength="<?= $escaper->escapeHtmlAttr($helper->getMaxQueryLength()) ?>"
                            role="combobox"
                            aria-haspopup="false"
                            aria-autocomplete="both"
                            autocomplete="off"
                            aria-expanded="false"/>
                        <div id="search_autocomplete" class="search-autocomplete"></div>
                        <?= $block->getChildHtml() ?>
                    </div>
                </div>
                <div class="actions active">
                    <button type="submit"
                            title="<?= $escaper->escapeHtml(__('Search')) ?>"
                            class="action search"
                            aria-label="Search"
                    >
                        <span><?= $escaper->escapeHtml(__('Search')) ?></span>
                    </button>
                </div>
            </form>
        </div>
    </div>
</div>
<script> 
    require(
    [
        'jquery'
    ],
    function($){
        $(document).ready(function() {
            $('.btn_search').click(function(){
                $(this).next().slideToggle()
            })
        })
    }
)
</script>