<ul class="wislist-header" name="wislist-header">
    <li class="link wishlist" data-bind="scope: 'wishlist'">
        <a <?= /* @noEscape */ $block->getLinkAttributes() ?>>
            <!-- ko if: wishlist().counter -->
            <span data-bind="text: wishlist().counter" class="counter qty"></span>
            <!-- /ko -->
        </a>
    </li>
</ul>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "wishlist": {
                        "component": "Magento_Wishlist/js/view/wishlist"
                    }
                }
            }
        }
    }

</script>
