<div class="switcher currency switcher-currency" id="switcher-currency">
    <div class="actions dropdown options switcher-options">
        <div class="action toggle switcher-trigger" id="switcher-currency-trigger" data-mage-init='{"dropdown":{}}' data-toggle="dropdown" data-trigger-keypress-button="true" aria-haspopup="true" aria-expanded="false" role="button" tabindex="0">
            <strong class="language-SGD">  
                <span data-text="SGDSGD">SGD</span>
            </strong>
        </div>
        <ul class="dropdown switcher-dropdown" data-target="dropdown" aria-hidden="true">  
            <li class="currency-MYR switcher-option">
                <a href="#" data-post="{&quot;action&quot;:&quot;https:\/\/www.curatiq.com\/directory\/currency\/switch\/&quot;,&quot;data&quot;:{&quot;currency&quot;:&quot;MYR&quot;}}">MYR</a>
            </li>    
        </ul>
    </div>
</div>

<script> 
    require(
    [
        'jquery'
    ],
    function($){
        $(document).ready(function() {
            $('.switcher-trigger').click(function(){
                $(this).next().slideToggle()
            })
        })
    }
)
</script>
