<div class="footer_guaranteed">
    <div class="container">
        <div class="main_guaranteed">
            <ul>
                <li>
                    <div class="guaranteed_item"><img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/footer/secure-shopping.svg" alt="">
                        <div class="guaranteed_title">Authenticity Guarantee</div>
                    </div>
                </li>
                <li>
                    <div class="guaranteed_item"><img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/footer/guaranteed.svg" alt="">
                    <div class="guaranteed_title">Secure Shopping Guarantee</div></div>
                </li>
                <li>
                    <div class="guaranteed_item"><img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/footer/fast.svg" alt="">
                        <div class="guaranteed_title">Fast Delivery</div>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>

