<div class="home-newsletter ">
    <div class="container">
        <div class="content-left">
            <h2>Stay Updated</h2>
            <p>Subscribe to our newsletter and enjoy 15% off your first purchase!</p>
        </div>
        <div class="block newsletter">
            <div class="content">
                <form class="form subscribe"
                    novalidate
                    action="<?= $block->escapeUrl($block->getFormActionUrl()) ?>"
                    method="post"
                    data-mage-init='{"validation": {"errorClass": "mage-error"}}'
                    id="newsletter-validate-detail">
                    <div class="field newsletter">
                        <div class="control_newsletter">
                            <input name="email" type="email" id="newsletter" class="mage-error"
                                placeholder="<?= $block->escapeHtml(__('Your Email Address')) ?>"
                                data-mage-init='{"mage/trim-input":{}}'
                                data-validate="{required:true, 'validate-email':true}"
                            />
                            <button class="action subscribe primary sr-only"
                                    title="SUBMIT"
                                    type="submit"
                                    aria-label="Subscribe">
                                <span><?= $block->escapeHtml(__('SUBMIT')) ?></span>
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Customer/js/block-submit-on-send": {
                "formId": "newsletter-validate-detail"
            }
        }
    }
</script>
