<div class="home-cate-wrapper">
    <div class="home-cate left" style="background-image: url(&quot;https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/post2.png&quot;);">
        <h3 class="hovermouse">Oral Supplements</h3>
        <div class="cate-inner">
            <div class="desktop hidden">
                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/post2.png" alt="" class="hidden">
            </div> 
            <div class="mobile">
                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/post2.png" alt="" class="hidden">
            </div>
            <h3 style="height: 45px;">Oral Supplements</h3>
            <p style="height: 140px;">Skin health starts from within<br>Strengthen your skin elasticity and radiance with oral supplements specially formulated to boost the quality of your skin</p>
            <p>
                <a title="LEARN MORE" href="https://www.curatiq.com/professional-products/uv-porcelain.html" style="height: 22px;">LEARN MORE</a>
            </p>
        </div>
    </div>
    <div class="home-cate mid" style="background-image: url(&quot;https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/post1.png&quot;);">
        <h3 class="hovermouse">Skin Care</h3>
        <div class="cate-inner">
            <div class="desktop hidden">
                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/post1.png" alt="" class="hidden">
            </div> 
            <div class="mobile hidden">
                <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/post1.png" alt="" class="hidden">
            </div>
            <h3 style="height: 45px;">Skin Care</h3>
            <p style="height: 140px;">Your skin deserves the best care<br>Develop a skincare routine that works for your specific skin type and addresses your personal skin concerns.</p>
            <p><a title="SHOP NOW" href="https://www.curatiq.com/e-shop.html/" style="height: 22px;">SHOP NOW</a></p>
        </div>
    </div>
    <div class="home-cate right" style="background-image: url(&quot;https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/post3.png&quot;);">
        <h3 class="hovermouse">Makeup</h3>
        <div class="cate-inner">
                <div class="desktop hidden">
                    <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/post3.png" alt="" class="hidden">
                </div> 
                <div class="mobile hidden">
                    <img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/post3.png" alt="" class="hidden">
                </div>
            <h3 style="height: 45px;">Makeup</h3>
            <p style="height: 140px;">Makeup that helps your skin shine<br>Enhance your look with makeup that cares for your skin. Consciously crafted with no nasty ingredients, find the right makeup products that leave your skin looking and feeling good.</p>
            <p><a title="SHOP NOW" href="https://www.curatiq.com/e-shop/makeup.html/" style="height: 22px;">SHOP NOW</a></p>
        </div>
    </div>
</div>
