<div class="home-about-wrapper" name="home.about" style="background-image: url(&quot;https://magento2.com/pub/static/frontend/Curatiq/curatiqq/en_US/images/hom-about/home-about-bgr.png&quot;);">
    <div class="home-about">
        <div class="content-left desktop">
            <img src="https://magento2.com/pub/static/frontend/Curatiq/curatiqq/en_US/images/hom-about/home-about-us_1.png" alt="">
        </div>
        <div class="content-left mobile">
            <img src="https://magento2.com/pub/static/frontend/Curatiq/curatiqq/en_US/images/hom-about/Mask_Group_9_2x.png" alt="">
        </div>
        <div class="content-right">
            <p class="heading">WHO WE ARE</p>
            <h3>Changing the Ideal of Beauty</h3>
            <h6>Welcome to Curatiq, your thoughtfully curated skincare and beauty boutique. Dedicated to sourcing high-performance skincare and beauty products that deliver what they promise, we introduce exclusive brands that focus on the science behind good skin.&nbsp;</h6>
            <p><a class="button" title="READ MORE" href="https://www.curatiq.com/about-us.html/">READ MORE</a></p></div>
        </div>
        <div class="home-brand container">
        <div class="content-left">
            <p class="heading">OUR CURATION</p>
            <h3>Explore the Brands</h3>
            <h6>We carefully source each brand we introduce to our online boutique to offer you a streamlined range of only the best products. Discover our curated skincare and make-up brands here!&nbsp;</h6>
            <p><a class="button" title="LEARN MORE" href="e-shop.html">LEARN MORE</a></p>
        </div>
        <div class="content-right desktop">
            <p class="heading"><img src="https://magento2.com/pub/static/frontend/Curatiq/curatiqq/en_US/images/hom-about/home-about-brand.png" alt=""></p>
        </div>
        <div class="content-right mobile">
            <p class="heading"><img src="https://magento2.com/pub/static/frontend/Curatiq/curatiqq/en_US/images/hom-about/home-brand-right-mb.png" alt=""></p>
        </div>
    </div>
    <div class="home-wrapper-image hidden"><img src="https://magento2.com/pub/static/frontend/Curatiq/curatiqq/en_US/images/hom-about/home-about-bgr.png" alt="">
    </div>
</div>