<div class="copyrights">
    <p>Copyright © <span id="copy-year">2022</span> Curatiq Pte Ltd. All rights reserved.<span class="vez-title">Web Excellence by <a class="icon-vez" href="https://www.curatiq.com/webagency/" target="_blank" rel="noopener">Verz</a> </span></p>
</div>
<div class="payment_method">
    <ul>
        <li><img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/footer/paypal.png" alt=""></li>
        <li><img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/footer/visa.png" alt=""></li>
        <li><img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/footer/mastercard.png" alt=""></li>
        <li><img src="https://magento2.com/app/design/frontend/Curatiq/curatiqq/web/images/footer/american-express.png" alt=""></li>
    </ul>
</div>